# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'ecoGame' do

#pod 'KDCircularProgress', '~> 1.4'
pod 'AFNetworking', '~> 3.1'
#pod 'QRCodeReader.swift', '~> 6.0.0'
pod 'HockeySDK', '~> 4.0'
#pod 'QRCode', '~> 0.5'
#pod 'ReachabilitySwift'

end

target 'ecoGameTests' do

end

target 'ecoGameUITests' do

end
